### PR TITLE
Restore 100% line coverage

### PR DESCRIPTION
**Pull request by bogdan-stefan-hs**
With the introduction of the [local storage lib](https://github.com/uberVU/react-component-playground/blob/0.3.x/src/lib/local-storage.js) in `local-storage.js`, line coverage has dropped below the initial 100%.

We need to restore it by refactoring the lib and/or adding more tests to cover all available cases.

### CODE REVIEW

**Comment by bogdan-stefan-hs** [comment]
@flavius-tirnacop-hs can you review the last commit?
It should be the only one left after #7 lands.

**Comment by flavius-tirnacop-hs** [comment]
LGTM but I don't think you really needed to branch from #7 as there are no dependencies between them (0.3.x would have been ok). I guess we can leave it as it is and wait for #7.

**Comment by bogdan-stefan-hs** [comment]
You're right, I didn't realize it at the time.

Here's the coverage report:
image

Can i merge this?

**Comment by flavius-tirnacop-hs** [comment]
Yes

**Pull request merged**
